version: "2.4"

services:
  pigen:
    image: mindspy/pigen:latest
    container_name: pigen
    cap_add:
      - SYS_ADMIN
      - SYS_CHROOT
      - CAP_MKNOD
    devices:
      - /dev
    device_cgroup_rules:
      - b 7:* rmw
    # networks:
    #   - proxy-net
    volumes:
      - /lib/modules:/lib/modules
      - ./deploy:/pi-gen/deploy
      - pigen-work:/pi-gen/work
    environment:
      - IMG_NAME=raspios
      # uncomment also networks tags if the proxy port is not published
      # - APT_PROXY=${PKG_PROXY}
      - STAGE_LIST=stage0 stage1 stage2
      - LOCALE_DEFAULT=en_US.UTF-8
      - ENABLE_SSH=1
      - DEPLOY_COMPRESSION=xz

  pigen-stage:
    extends:
      service: pigen
    image: mindspy/pigen:latest-stage
    platform: ${platform}
    container_name: pigen-stage
    environment:
      - STAGE_LIST=stage0 stage1 stage2
      - STAGE_PREFIX=stage

  pigen-export:
    extends:
      service: pigen
    image: mindspy/pigen:latest-export
    container_name: pigen-export
    environment:
      - STAGE_LIST=stage2
      - STAGE_PREFIX=export

  dev:
    extends:
      service: pigen
    image: mindspy/pigen:dev
    container_name: pigen-dev
    entrypoint:
      - sleep
      - infinity

volumes:
  pigen-work:
    name: pigen-work

# networks:
#   proxy-net:
#     name: ${PKG_PROXY_NET}
#     external: true
